silicon/__init__.py
import os
from pathlib import Path
import secrets
import sys

from flask import Flask


def create_app(test_config=None):
    """
    Create the application object, sprinkle in some configuration,
    add our commands, add views, and return the app.

    Note that Flask has a system for putting config files into the instance
    path but we are opting to use environment variables instead, to avoid
    having to manage configuration in different places.

    `app.instance_path` is the directory where the database and secret key are
    stored.

    Flask requires a secret key for session handling. If one was provided in
    the environment, we use that. Otherwise, we try to read one from a file
    in the instance path. If that fails, we generate a new key and write it out
    to disk.
    """
    instance_path = os.getenv('INSTANCE_PATH', None)

    if instance_path is not None:
        app = Flask(__name__, instance_path=instance_path)
    else:
        # Flask defaults to setting `instance_path` to a directory named
        # `instance` next to the package.
        app = Flask(__name__)

    if test_config:
        app.config.update(test_config)
    else:
        # ensure the instance folder exists
        os.makedirs(app.instance_path, exist_ok=True)

        if app.debug:
            print(sys.version)
            print(f"Instance path: {app.instance_path}")

        app.config['DATABASE'] = os.path.join(
            app.instance_path, 'silicon.sqlite')

        app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', None)

    if app.config['SECRET_KEY'] is None:
        # try to read the secret key
        secret_key_path = Path(app.instance_path) / 'secret.key'
        try:
            app.config['SECRET_KEY'] = secret_key_path.read_bytes()
        except FileNotFoundError:
            # generate and save a new one
            app.config['SECRET_KEY'] = secrets.token_bytes(16)
            os.umask(0)
            secret_key_fd = os.open(
                secret_key_path, os.O_CREAT | os.O_WRONLY, 0o600)
            with open(secret_key_fd, 'wb') as f:
                f.write(app.config['SECRET_KEY'])

    app.config['SILICON_EDITOR'] = os.getenv('SILICON_EDITOR', 'codemirror')

    from . import commands
    commands.init_app(app)

    from . import views
    app.register_blueprint(views.bp)

    return app

silicon/views.py
from pathlib import Path

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)

from silicon.j2_filters import human_timestamp, mark_query_results
from silicon.render_md import md_renderer, toc_renderer
from silicon.util import slugify_title
from silicon import page, related


bp = Blueprint('page', __name__)
bp.add_app_template_filter(human_timestamp)
bp.add_app_template_filter(mark_query_results)


@bp.route('/view/')
@bp.route('/edit/')
@bp.route('/history/')
@bp.route('/')
def home():
    return redirect(url_for(f'{bp.name}.view', title='home'))


@bp.route('/view/<title>')
def view(title):
    slugified_title = slugify_title(title)

    if slugified_title != title:
        return redirect(url_for("page.view", title=slugified_title))

    if 'revision' in request.args:
        p = page.read(title, request.args.get('revision'))
    else:
        p = page.read(title)
        p['relatives'] = related.get(title)
        if 'body' in p:
            p['toc'] = toc_renderer(p['body'])

    if p['revision'] is None:
        return render_template('not_found.html.j2', **p), 404
    else:
        p['html'] = md_renderer(p['body'])
        return render_template('view.html.j2', **p)


@bp.route('/edit/<title>', methods=['GET', 'POST'])
def edit(title):
    slugified_title = slugify_title(title)

    if slugified_title != title:
        return redirect(url_for("page.edit", title=slugified_title))

    p = page.read(title)
    p['relatives'] = related.get(title)
    if 'body' in p:
        p['toc'] = toc_renderer(p['body'])
    if request.method == 'GET':
        return render_template('edit.html.j2', **p)
    elif request.method == 'POST':
        if 'body' not in request.form:
            flash('"body" field missing!')
            return render_template('edit.html.j2', **p)
        # was there a previous revision of the page?
        if p['revision'] is None:
            p['body'] = None
        # only save the page if the new text differs from previous revision
        if p['body'] != request.form['body']:
            error = page.write(title, request.form['body'])
            if error:
                flash(error)
                return render_template(
                    'edit.html.j2', title=title, body=request.form['body'])
        return redirect(url_for(f'{bp.name}.view', title=title))


@bp.route('/history/<title>')
def history(title):
    p = {}
    p['title'] = slugify_title(title)
    p['revisions'] = page.history(p['title'])
    p['count'] = len(p['revisions'])
    if p['count'] == 0:
        return render_template('not_found.html.j2', **p), 404
    return render_template('history.html.j2', **p)


@bp.route('/history/<title>/<req_revision>')
def history_revision(title, req_revision):
    title = slugify_title(title)

    p = page.read(title, req_revision)

    # req_revision not found, redirect back to history index
    if p['revision'] is None:
        return redirect(url_for(f'{bp.name}.history', title=title))

    p['req_revision'] = req_revision
    p['revisions'] = page.history(title)
    p['count'] = len(p['revisions'])
    p['html'] = md_renderer(p['body'])
    p['toc'] = toc_renderer(p['body'])

    return render_template('history.html.j2', **p)


@bp.route('/docs', defaults={'title': 'main'})
@bp.route('/docs/<title>')
def docs(title):
    p = {}

    p['title'] = slugify_title(title)

    doc = Path(__file__).parent / 'docs' / f'{title}.md'
    try:
        with doc.open() as f:
            body = f.read()
            p['html'] = md_renderer(body)
    except FileNotFoundError:
        p['html'] = f'No documentation for "{title}" found.'
        return render_template('docs.html.j2', **p), 404

    p['toc'] = toc_renderer(body)
    return render_template('docs.html.j2', **p)


@bp.route('/search')
def search():
    def render_template_err(msg):
        return render_template(
            'search.html.j2',
            err_msg=msg,
            title="Invalid Query"
        )

    query = request.args.get('query', '').strip()
    slugified_query = slugify_title(query)

    if not query:
        return render_template_err('No query specified.'), 400
    try:
        title_results, body_results = page.search(request.args['query'])
    except page.SearchError as err:
        return render_template_err(err), 400

    for i in range(len(title_results)):
        if title_results[i]['title'] == slugified_query:
            exact_match = title_results.pop(i)
            title_results.insert(0, exact_match)
            break

    return render_template(
        'search.html.j2', title=f"Results for '{query}'",
        title_results=title_results, body_results=body_results)


@bp.route('/toc', methods=['POST'])
def toc():
    if 'body' not in request.form:
        return 'Invalid request', 400
    return toc_renderer(request.form['body'])


@bp.route('/related/<title>')
def get_relatives(title):
    return render_template(
        'related.html.j2', title=title, relatives=related.get(title))


@bp.route('/related/<title>', methods=['POST'])
def add_relative(title):
    if 'relative' in request.form:
        related.add(title, request.form['relative'])
    return render_template(
        'related.html.j2', title=title, relatives=related.get(title))


@bp.route('/related/<title>/<relative>', methods=['DELETE'])
def delete_relative(title, relative):
    related.delete(title, relative)
    return render_template(
        'related.html.j2', title=title, relatives=related.get(title))

silicon/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{{ title }}</title>
  {% block links %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/colors.css') }}" type="text/css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" type="text/css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}" type="text/css" media="screen">
  {% endblock %}
  {% block scripts %}
  <script src="{{ url_for('static', filename='js/main.js') }}" defer></script>
  {% endblock %}
<body>

  <div class="grid-for-nav">
    <!-- this is the whole left sidebar -->
    <nav class="nav-side" data-toggle="nav-shift">
      <!-- this is the scrollable area of the nav sidebar-->
      <div class="side-scroll">
        <!-- this is the menu part of the sidebar -->
        <div class="menu-vertical" data-spy="affix" role="navigation" aria-label="main naviation">

          <div class="nav-page-title">
            <a href="{{ url_for('page.view', title=title) }}" class="page-title">{{ title }}</a>
          </div>

          {% block sidebar_contents %}{% endblock %}

        </div>
      </div>
    </nav>
    <!-- this contains the "mobile" nav and content -->
    <section class="nav-content-wrap" data-toggle="nav-shift">
      <!-- this contains the hamburger menu and title for mobile -->
      <nav class="nav-top" aria-label="top navigation">
        <button class="menu-toggle" data-toggle="nav-top">Nav</button>
        <span class="page-title" href="#">{{ title }}</span>
        <!-- this is dumb but I really want the page title to be centered
             rather than slightly offset to the right -->
        <button class="menu-toggle" style="visibility: hidden;">Nav</button>
      </nav>

      {% block content %}{% endblock %}

    </section>
  </div>

  <div class="nav-bottom" data-toggle="nav-shift" role="note">
    <form class="nav-form" action="/search" method="get">
      <div class="nav-input-wrap">
        <input id="search" name="query" type="text" placeholder="🔍 Search">
      </div>
    </form>
  </div>

</body>
</html>

silicon/templates/docs.html.j2
{% import "macros.html.j2" as macros %}
{% extends "base.html.j2" %}

{% block links %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/print.css') }}" type="text/css" media="print">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/pygments.css') }}" type="text/css" media="screen">
  {{ macros.favicons() }}
{% endblock %}

{#
{% block scripts %}
  {{ super() }}
  <script src="{{ url_for('static', filename='js/widgets.js') }}" defer></script>
{% endblock %}
#}

{% block sidebar_contents %}
  {{ macros.nav_links(title, 'home', 'docs') }}

  {{ macros.table_of_contents(title, toc) }}
{% endblock %}

{% block content %}
  <div class="nav-content">
    <article>
        {{ html|safe }}
    </article>
  </div>
{% endblock %}

silicon/templates/edit.html.j2
{% import "macros.html.j2" as macros %}
{% extends "base.html.j2" %}

{% block links %}
  {{ super() }}
  {% if config.SILICON_EDITOR == 'codemirror' %}
    <link rel=stylesheet href="{{ url_for('static', filename='node_modules/codemirror/lib/codemirror.css') }}">
  {% endif %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/edit.css') }}" type="text/css" media="screen">
  {{ macros.favicons('edit') }}
{% endblock %}

{% block scripts %}
  {{ super() }}
  {% if config.SILICON_EDITOR == 'codemirror' %}
    <script src="{{ url_for('static', filename='node_modules/requirejs/require.js') }}" defer></script>
  {% endif %}
  <script type="text/javascript">
    const js_modules_root = "{{ url_for('static', filename='node_modules') }}";
    const silicon_editor = "{{ config.SILICON_EDITOR }}";
  </script>
  <script src="{{ url_for('static', filename='js/widgets.js') }}" defer></script>
  <script src="{{ url_for('static', filename='js/edit.js') }}" defer></script>
{% endblock %}

{% block sidebar_contents %}
  {{ macros.nav_links(title, 'docs') }}

  <div class="nav-button-wrap">
    <input class="nav-button" type="Submit" form="page-form" value="Save">
    <a class="nav-button" href="{{ url_for('page.view', title=title) }}">Cancel</a>
  </div>

  <div id="alert-box">
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul id="alerts">
          {% for message in messages %}
          <li class="alert">{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
  </div>

  {{ macros.related(title, relatives) }}
  {{ macros.table_of_contents(title, toc) }}
{% endblock %}

{% block content %}
  <form action="{{ url_for('page.edit', title=title) }}" id="page-form" method="post">
    <textarea id="body-text" name="body">{{ body|e }}</textarea>
  </form>
{% endblock %}

silicon/templates/history.html.j2
{% import "macros.html.j2" as macros %}
{% extends "base.html.j2" %}

{% block links %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/print.css') }}" type="text/css" media="print">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/pygments.css') }}" type="text/css" media="screen">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/history.css') }}" type="text/css" media="screen">
  {{ macros.favicons() }}
{% endblock %}

{% block sidebar_contents %}
  {{ macros.nav_links(title, 'home', 'docs') }}

  <div class="nav-header">Revisions: {{ count }}</div>

  <table id="revisions">
    <tbody>
    {% for r in revisions %}
      <tr>
      {% if r == req_revision %}
        <td id="current-revision">
      {% else %}
        <td>
      {% endif %}
          <a href="{{ url_for('page.history_revision', title=title, req_revision=r) }}">{{ r|human_timestamp }}</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  {% if req_revision %}
    {{ macros.table_of_contents(title, toc) }}
  {% endif %}

{% endblock %}

{% block content %}
  <div class="nav-content">
    {% if req_revision %}
      <div id="revision-notice">Revision from {{ req_revision|human_timestamp }}</div>
    {% endif %}
    <article>
      {% if html %}
        {{ html|safe }}
      {% else %}
        <p>Select a revision from the list.</p>
      {% endif %}
    </article>
  </div>
{% endblock %}

silicon/templates/macros.html.j2
{#
 # Render favicon links
 #
 # Params:
 # * mode: `view` (default) or `edit`
#}
{% macro favicons(mode='view') %}
  <link rel="icon" sizes="16x16 32x32 48x48" href="{{ url_for('static', filename='img') }}/favicon-{{ mode }}.ico">
  <link rel="icon" type="image/png" sizes="192x192" href="{{ url_for('static', filename='img') }}/favicon-{{ mode }}-192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img') }}/favicon-{{ mode }}-32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img') }}/favicon-{{ mode }}-16.png">
{% endmacro %}

{#
 # Render the nav links bar
 #
 # Params:
 # * title: title of the current page
 # * _varargs_: `history`, `home`, and/or `docs`
 #}
{% macro nav_links(title) %}
  <div class="nav-page-links">
    [
    {%- for link in varargs -%}
      {%- if link == 'history' -%}
        <a href="{{ url_for('page.history', title=title) }}">History</a>
      {%- elif link == 'home' -%}
        <a href="{{ url_for('page.view', title='home') }}">Home</a>
      {%- elif link == 'docs' -%}
        <a href="{{ url_for('page.docs') }}" target="_blank">Docs</a>
      {%- endif -%}
      {%- if not loop.last %} | {% endif -%}
    {%- endfor -%}
    ]
  </div>
{% endmacro %}

{#
 # Render related pages
 #
 # Params:
 # title: title of the current page
 # relatives: list of pages relatives as an array
 #}
{% macro related(title, relatives) %}
  <div class="nav-header">
    Related
    <span class="widget-title-span">
      [<span class="widget-title-btn" id="add-relation-btn">add</span>]
    </span>
  </div>
  <div id="related-links" data-widget-url="{{ url_for('page.get_relatives', title=title) }}">
    {% include "related.html.j2" %}
  </div>
{% endmacro %}

{#
 # Render table of contents
 # title: title of the current page
 # toc: pre-rendered table of contents
 #}
{% macro table_of_contents(title, toc) %}
  <div class="nav-header">
    Contents
    <span class="widget-title-span" id="update-toc" style="visibility: hidden">
      [<span class="widget-title-btn" id="update-toc-btn">update</span>]
    </span>
  </div>
  <div id="toc" data-widget-url="{{ url_for('page.toc') }}">{{ toc }}</div>
{% endmacro %}

silicon/templates/not_found.html.j2
{% import "macros.html.j2" as macros %}
{% extends "base.html.j2" %}

{% block links %}
  {{ super() }}
  {{ macros.favicons() }}
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script src="{{ url_for('static', filename='js/widgets.js') }}" defer></script>
{% endblock %}

{% block sidebar_contents %}
  {{ macros.nav_links(title, 'home', 'docs') }}

  <div class="nav-button-wrap">
    <a class="nav-button" href="{{ url_for('page.edit', title=title) }}">Edit</a>
  </div>

  {{ macros.related(title, relatives) }}
{% endblock %}

{% block content %}
  <!-- main content area wrapper -->
  <div class="nav-content">
    <article>
      <h1>Not Found</h1>

      Page does not exist. Perhaps you would like to
      <a class="internal-link" href="{{ url_for('page.edit', title=title) }}">create it</a>?
    </article>
  </div>
{% endblock %}

silicon/templates/related.html.j2
<ul>
{% for rel in relatives -%}
  <li class="related-page">
    <a class="internal-link" href="{{ url_for('page.view', title=rel) }}">
      {{ rel }}
    </a>
    <span class="del-relation">
      [<span class="del-relation-btn" data-del-relative="{{ rel }}">remove</span>]
    </span>
  </li>
{% endfor -%}
</ul>

silicon/templates/search.html.j2
{% import "macros.html.j2" as macros %}
{% extends "base.html.j2" %}

{% block links %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/print.css') }}" type="text/css" media="print">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/pygments.css') }}" type="text/css" media="screen">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/search.css') }}" type="text/css" media="screen">
  {{ macros.favicons() }}
{% endblock %}

{% block sidebar_contents %}
  {{ macros.nav_links(title, 'home', 'docs') }}

  <div class="nav-header">Search Tips</div>

  <ul id="search-tips">
    <li>Search terms are case-insensitive</li>
    <li><code>AND</code>, <code>OR</code>, and <code>NOT</code>: boolean operators</li>
    <ul>
      <li><code>AND</code> is the default</li>
      <li>Must be uppercase</li>
    </ul>
    <li><code>"double quotes"</code>: phrase search</li>
    <li><code>foo*</code>: prefix search</li>
    <li><code>^foo</code>: title or page starts with <code>foo</code></li>
  </ul>

{% endblock %}

{% block content %}
  <div class="nav-content">
    <article>
    {% if err_msg %}
      <p class="err-msg">{{ err_msg }}</p>
    {% else %}
      {% if title_results %}
        <b>Title matches:</b>
        <ul class="title-matches">
        {% for t_result in title_results %}
          <li>
            <a class="internal-link" href="{{ url_for('page.view', title=t_result['title']) }}">
              {{ t_result['snippet']|mark_query_results }}
            </a>
          </li>
        {% endfor %}
        </ul>
        {% else %}
        <p>No title matches.</p>
      {% endif %}

      {% if body_results %}
      <b>Body matches:</b>
        <dl class="body-matches">
        {% for b_result in body_results %}
          <dt class="result_title">
            <a class="internal-link" href="{{ url_for('page.view', title=b_result['title']) }}">
              {{ b_result['title'] }}
            </a>
          </dt>
          <dd class="result_body">{{ b_result['snippet']|mark_query_results }}</dd>
        {% endfor %}
        </dl>
        {% else %}
        <p>No body matches.</p>
      {% endif %}
    {% endif %}
    </article>
  </div>
{% endblock %}

silicon/templates/view.html.j2
{% import "macros.html.j2" as macros %}
{% extends "base.html.j2" %}

{% block links %}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/print.css') }}" type="text/css" media="print">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/pygments.css') }}" type="text/css" media="screen">
  {{ macros.favicons() }}
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script src="{{ url_for('static', filename='js/widgets.js') }}" defer></script>
{% endblock %}

{% block sidebar_contents %}
  {{ macros.nav_links(title, 'history', 'home', 'docs') }}

  <div class="nav-button-wrap">
    <a class="nav-button" href="{{ url_for('page.edit', title=title) }}">Edit</a>
  </div>

  <div class="nav-page-timestamp">Edited: {{ revision|human_timestamp }}</div>

  {{ macros.related(title, relatives) }}
  {{ macros.table_of_contents(title, toc) }}
{% endblock %}

{% block content %}
  <div class="nav-content">
    <article>
        {{ html|safe }}
    </article>
  </div>
{% endblock %}